#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jun 14 11:58:29 2018

@author: samyukthanagesh
"""

"""
Exploring the 'fill' function.
"""
import numpy as np
import matplotlib.pyplot as plt
#import math

"""
#1st code block: only one color filling
x = np.linspace(0, 1)
y = np.sin(4 * np.pi * x) * np.exp(-5 * x)

plt.fill(x, y, 'g')
plt.grid(True)
plt.show()
"""
#2nd code block:multiple colors
x = np.linspace(0, 2 * np.pi, 100)
y1 = np.sin(x)
y2 = np.sin(3 * x)
#y3= math.asin(x) will throw an error: x and y have to be same size to plot- explore later
y3 = np.cos (x)
plt.fill(x, y1, 'b', x, y2, 'r', x, y3, 'g', 
        alpha=0.3)
plt.show()

"""
#3rd code block: to get dotted line graph

x = np.linspace(0, 10)
line, = plt.plot(x, np.sin(x), '--', linewidth=2)

dashes = [1, 1, 1, 1]  # 10 points on, 5 off, 100 on, 5 off
line.set_dashes(dashes)

plt.show()
"""
